from typing import Any, Optional

from pydantic import BaseModel, Field


class ProblemDetails(BaseModel):
    """
    RFC 7807 (Problem Details for HTTP APIs) compliant error response.
    """

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type.",
        json_schema_extra={"example": "https://example.com/probs/out-of-stock"},
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type.",
        json_schema_extra={"example": "You do not have enough credit."},
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server for this occurrence of the problem.",
        json_schema_extra={"example": 404},
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
        json_schema_extra={"example": "Dataset with id '123' was not found."},
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        json_schema_extra={"example": "/datasets/123"},
    )
    extension: Optional[dict[str, Any]] = Field(
        None, description="Optional additional members to extend the problem detail object."
    )
