from typing import Any, Optional

from pydantic import BaseModel, Field


class ProblemDetails(BaseModel):
    """
    RFC 7807 (Problem Details for HTTP APIs) compliant error response.
    """

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type.",
        example="https://example.com/probs/out-of-stock",
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type.",
        example="You do not have enough credit.",
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server for this occurrence of the problem.",
        example=403,
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
        example="Your current balance is 30, but the costs is 50.",
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        example="/account/12345/msgs/abc",
    )
    extension: Optional[dict[str, Any]] = Field(
        None, description="Optional additional members to extend the problem detail object."
    )
