/**
 * Mock data for testing
 */

import type { DatasetSummary } from "../types/datasets";

export const mockDatasets: DatasetSummary[] = [
  {
    id: "dataset-1",
    platformId: "f8409d32-651e-45c8-bfbc-d6587089f5e3",
    platformName: "data.gouv.fr",
    platformType: "datagouv",
    title: "Test Dataset 1",
    page: "https://www.data.gouv.fr/datasets/test-1",
    publisher: "Test Publisher",
    created: "2024-01-01T00:00:00Z",
    modified: "2024-01-10T00:00:00Z",
    published: true,
    restricted: false,
    downloadsCount: 100,
    apiCallsCount: 50,
    viewsCount: 1000,
    reusesCount: 5,
    followersCount: 10,
    versionsCount: 3,
    lastSyncStatus: "success",
    hasDescription: true,
    isDeleted: false,
  },
  {
    id: "dataset-2",
    platformId: "a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6",
    platformName: "data.economie.gouv.fr",
    platformType: "opendatasoft",
    title: "Test Dataset 2",
    page: "https://data.economie.gouv.fr/explore/dataset/test-2",
    publisher: null,
    created: "2024-01-05T00:00:00Z",
    modified: "2024-01-15T00:00:00Z",
    published: false,
    restricted: true,
    downloadsCount: 200,
    apiCallsCount: 150,
    viewsCount: 2000,
    reusesCount: 0,
    followersCount: 0,
    versionsCount: 1,
    lastSyncStatus: "pending",
    hasDescription: false,
    isDeleted: false,
  },
  {
    id: "dataset-3",
    platformId: "f8409d32-651e-45c8-bfbc-d6587089f5e3",
    platformName: "data.gouv.fr",
    platformType: "datagouv",
    title: "Deleted Dataset",
    page: "https://www.data.gouv.fr/datasets/deleted",
    publisher: "Publisher",
    created: "2023-01-01T00:00:00Z",
    modified: "2023-06-01T00:00:00Z",
    published: true,
    restricted: false,
    downloadsCount: 50,
    apiCallsCount: 25,
    viewsCount: 500,
    reusesCount: 2,
    followersCount: 3,
    versionsCount: 5,
    lastSyncStatus: "failed",
    hasDescription: true,
    isDeleted: true,
  },
];
