-- ============================================================================
-- Unified Impact Score - Weekly Momentum
-- ============================================================================

-- Hypothèses :
-- - Compteurs cumulés monotones (pas de reset sauvage).
-- - Impact mesuré comme ELAN hebdomadaire (deltas), pas comme stock cumulé.
-- - Poids à calibrer métier : vues=1, téléchargements=2, appels API=0.5,
--   +30 / nouveau follower, +80 / nouvelle réutilisation, +10 si dataset < 90j.
-- ============================================================================
\COPY (WITH weekly_points AS (SELECT d.id, d.slug, d.created, d.publisher, p.type AS platform_type, p.name AS platform, FIRST_VALUE(dv.views_count) OVER w AS start_views, LAST_VALUE(dv.views_count) OVER w AS end_views, FIRST_VALUE(dv.api_calls_count) OVER w AS start_api, LAST_VALUE(dv.api_calls_count) OVER w AS end_api, FIRST_VALUE(dv.downloads_count) OVER w AS start_dl, LAST_VALUE(dv.downloads_count) OVER w AS end_dl, FIRST_VALUE(dv.followers_count) OVER w AS start_followers, LAST_VALUE(dv.followers_count) OVER w AS end_followers, FIRST_VALUE(dv.reuses_count) OVER w AS start_reuses, LAST_VALUE(dv.reuses_count) OVER w AS end_reuses FROM dataset_versions dv JOIN datasets d ON d.id = dv.dataset_id JOIN platforms p ON p.id = d.platform_id WHERE dv.timestamp >= CURRENT_DATE - INTERVAL '1 week' AND d.deleted IS FALSE WINDOW w AS (PARTITION BY d.id ORDER BY dv.timestamp RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)), weekly_delta AS (SELECT DISTINCT id, slug, created, publisher, platform_type, platform, GREATEST(0, end_views - start_views) AS delta_views, GREATEST(0, end_api - start_api) AS delta_api, GREATEST(0, end_dl - start_dl) AS delta_dl, GREATEST(0, end_followers - start_followers) AS followers_gain, GREATEST(0, end_reuses - start_reuses) AS reuses_gain FROM weekly_points), scored_datasets AS (SELECT slug, publisher, platform, platform_type, CASE WHEN platform_type = 'opendatasoft' THEN (delta_dl * 2.0) + (delta_api * 0.5) ELSE (delta_views * 1.0) END AS weighted_activity, followers_gain, reuses_gain, CASE WHEN created >= CURRENT_DATE - INTERVAL '90 days' THEN 10 ELSE 0 END AS freshness_bonus FROM weekly_delta), final_scores AS (SELECT slug, publisher, platform, platform_type, ROUND(LN(1 + weighted_activity) * 15, 2) AS activity_score, followers_gain * 30 AS engagement_score, reuses_gain * 80 AS reuse_score, freshness_bonus AS freshness_score, ROUND((LN(1 + weighted_activity) * 15) + (followers_gain * 30) + (reuses_gain * 80) + freshness_bonus, 2) AS unified_impact_score, weighted_activity AS raw_activity_index, followers_gain AS weekly_followers_gain, reuses_gain AS weekly_reuses_gain FROM scored_datasets WHERE weighted_activity > 0 OR followers_gain > 0 OR reuses_gain > 0) SELECT slug, publisher, platform, platform_type, unified_impact_score, activity_score, engagement_score, reuse_score, freshness_score, raw_activity_index, weekly_followers_gain, weekly_reuses_gain FROM final_scores ORDER BY unified_impact_score DESC LIMIT 25) TO STDOUT WITH CSV HEADER;
